import callbacks as cb
async_complete = cb.Callbacks("async_complete")
controller = cb.Callbacks("controller")
init = cb.Init()
listener = cb.Callbacks("listener")
midi_in = cb.Callbacks("midi_in")
note = cb.Callbacks("note")
nrpn = cb.Callbacks("nrpn")
persistence_changed = cb.Callbacks("persistence_changed")
pgs_changed = cb.Callbacks("pgs_changed")
poly_at = cb.Callbacks("poly_at")
release = cb.Callbacks("release")
rpn = cb.Callbacks("rpn")
ui_update = cb.Callbacks("ui_update")
